theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache

# Basic Settings
title: "Nicholas Rathmann"
#subtitle: "<affiliation>"
locale: "en-US"

# Specific Theme Settings
minimal_mistakes_skin: "mint" # Options: air, aqua, contrast, etc.

site_navigation: main

collections:
  research:
    output: true
    permalink: /research/:path/
  publications:
    output: false
    permalink: /publications/:path/
  teaching:
    output: false
    permalink: /teaching/:path/
  software:
    output: false
    permalink: /software/:path/

footer:
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=frOklkgAAAAJ"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Nicholas-Rathmann"
    - label: "ORCID"
      icon: "fa-brands fa-orcid"
      url: "https://orcid.org/0000-0001-7140-0931"      
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nicholasmr"

defaults:
  - scope:
      path: ""
      type: "research" # This targets everything in the _research folder
    values:
      layout: "splash"
      author_profile: false
